/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdPosts: typeof import('./src/components/AdPosts.vue')['default']
    ErrorState: typeof import('./src/components/ErrorState.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HomeSkeleton: typeof import('./src/components/HomeSkeleton.vue')['default']
    MainStories: typeof import('./src/components/MainStories.vue')['default']
    MissedStories: typeof import('./src/components/MissedStories.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PopularStories: typeof import('./src/components/PopularStories.vue')['default']
    PostBodyEditor: typeof import('./src/components/PostBodyEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Stories: typeof import('./src/components/Stories.vue')['default']
  }
}
